spring:
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true

logging:
  level:
    root: INFO
    io.github.smaykell.aulavirtual: INFO

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
